jwt:
  time: 90000
  secret: hello-world1234412121
posco:
  name: 3ê¸°444412121
  count: 2044441212
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: "{cipher}ba4cbf13d44262a17c150c1426023a6da4c2d1d904f83496abcd071c7b5ac629"
