posco:
  name: 3ê¸°444412312312312
  count: 20444412312312312312
test:
  datasource:
    url: jdbc:mysql://?.?.?.?:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
    username: rollin
    password: 1234
jwt:
  secret_key: SECRET_APPLESECRET_APPLESECRET_APPLESECRET_APPLE
  expTime: 86400000
