jwt:
  time: 90000
  secret: hello-world123441212
posco:
  name: 3ê¸°44441212
  count: 2044441212
test:
  datasource:
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
